# Generated by Django 5.2.16 on 2026-07-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('activities', models.TextField()),
                ('accomplishments', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('lessons_learnt', models.TextField(blank=True, null=True)),
                ('supervisor_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
            ],
            options={
                'ordering': ['-month', '-submitted_at'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
